### PR TITLE
Front-end Skeleton

### PR DESCRIPTION
**Pull request by lattln**
Let me know if I'm missing anything.

### CODE REVIEW

**Comment by Nguyen-Noah** [comment]
Can you write a description highlighting the features you implemented and how some of the directories/libraries you created can be used/modified

**Comment by lattln** [comment]
> Can you write a description highlighting the features you implemented and how some of the directories/libraries you created can be used/modified

It's inside bulk additions, but I can write a more detail one later. I can also give a run down in a meeting

**Review by Nguyen-Noah — APPROVED** [review]

**Review by CollinFoord — APPROVED** [review]
Looks good!

**Comment by lattln** [comment]
2/2 Approval 👍 Merging

**Pull request merged**
